Repository cloudflare/cfssl, pull requests merged in 2018-03, with the labels that each got.

#879 errors: add OCSPError case to errors.Wrap.
  errors/error.go
Labels: bug

#878 Various SCT related cleanups
  certdb/testdb/certstore_development.db
  helpers/helpers.go
  helpers/helpers_test.go
  ocsp/testdata/sqlite_test.db
  signer/local/local_test.go
Labels: enhancement

#880 Release 1.3.2.
  cli/version/version.go
  cli/version/version_test.go
Labels: release
